### ISSUE TITLE
*** Process received signal ***

### ISSUE THREAD

**Issue by chivesab** [Drapegnik/merge_sort#1]
I try to run your code but there's an error message : 『Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.  』

mpirun noticed that process rank 0 with PID 0 on node MyMacBook-Pro-2 exited on signal 6 (Abort trap: 6).

I have no idea what's going on

**Comment by Drapegnik** [comment]
> I have no idea what's going on

So do I.
Sorry, it was a long time ago...
